[ECSOSB-294] Relax verification for remote connection creation
thecodeteam/ecs-cf-service-broker pull request #246
Opened 2023-08-08 23:12 UTC by napand

2023-08-09 20:33 UTC, twincitiesguy requested changes

2023-08-09 20:33 UTC, twincitiesguy commented on src/main/java/com/emc/ecs/servicebroker/service/RemoteConnectionInstanceWorkflow.java
> +        Map<String, Object> settings = ecs.mergeParametersForRemoteConnections(serviceDef, plan);
instead of creating a new method, can you call `ecs.mergeParameters(serviceDef, plan, new HashMap<>())`?

2023-08-09 21:49 UTC, napand commented on src/main/java/com/emc/ecs/servicebroker/service/RemoteConnectionInstanceWorkflow.java
> +        Map<String, Object> settings = ecs.mergeParametersForRemoteConnections(serviceDef, plan);
The methods are very different.
mergeParametersForRemoteConnections will not include request parameters (the empty HashMap) and also not include tags and search metadata.

2023-08-10 16:52 UTC, twincitiesguy requested changes

2023-08-10 16:52 UTC, twincitiesguy commented on src/main/java/com/emc/ecs/servicebroker/service/RemoteConnectionInstanceWorkflow.java
> +        settings.remove(TAGS);
instead of removing these tags _**only**_ from the local settings, we need to exclude them from the comparison - that way, if they are present on either side (local or remote), they will be excluded

2023-08-10 16:52 UTC, twincitiesguy commented on src/main/java/com/emc/ecs/servicebroker/service/RemoteConnectionInstanceWorkflow.java
> +
`settingsDiff` is the map from which we should remove `TAGS` and `SEARCH_METADATA` as keys - we can either do that in the stream as part of filtering, or simply call `remove()` after the filter.  This way, regardless of where these settings are (local or remote), they will be excluded from the comparison.

2023-08-10 17:12 UTC, napand commented on src/main/java/com/emc/ecs/servicebroker/service/RemoteConnectionInstanceWorkflow.java
> +        settings.remove(TAGS);
I removed tags and search metadata from both the local and remote settings.

2023-08-10 17:13 UTC, napand commented on src/main/java/com/emc/ecs/servicebroker/service/RemoteConnectionInstanceWorkflow.java
> +
I removed tags and search metadata from both the local and remote settings.
The diff is done recursively and is better to remove them before the diff.

2023-08-10 19:13 UTC, twincitiesguy approved these changes

2023-08-10 20:15 UTC, merged